services:
  backend:
    build: 
      context: .
      dockerfile: packages/backend/Dockerfile.dev
    ports:
      - "3001:3001"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/packages/backend/node_modules
      - /app/packages/shared/node_modules
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/pomodoro
      - REDIS_URL=redis://redis:6379
      - NODE_ENV=development
      - NEST_PORT=3001

  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pomodoro
    volumes:
      - pgdata-dev:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

volumes:
  pgdata-dev: